version = 0.1

[default.deploy.parameters]
stack_name = "mirconaut-aws-lambda-graalvm-maven"
resolve_s3 = true
s3_prefix = "mirconaut-aws-lambda-graalvm-maven"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
confirm_changeset = true
